<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-06-08 08:49
=======
# Generated by Django 5.2.1 on 2025-05-31 04:56
>>>>>>> 5a4edcb6a4c3843af1a3137a75cee3f06ca8229b

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('interestID', models.AutoField(primary_key=True, serialize=False, verbose_name='관심사ID')),
                ('interestName', models.CharField(max_length=100, unique=True, verbose_name='관심사명')),
            ],
            options={
                'verbose_name': '관심사',
                'verbose_name_plural': '관심사들',
                'db_table': 'interests',
                'ordering': ['interestName'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('accountID', models.CharField(max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='계정ID')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('accountType', models.CharField(choices=[('student', '학생'), ('instructor', '강사'), ('admin', '관리자')], default='student', max_length=20, verbose_name='계정타입')),
                ('joinDate', models.DateField(auto_now_add=True, verbose_name='가입일')),
                ('name', models.CharField(max_length=45, verbose_name='이름')),
                ('phoneNum', models.CharField(max_length=45, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=45, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='이메일')),
                ('birth', models.DateField(verbose_name='생년월일')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원들',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False, verbose_name='클래스ID')),
                ('className', models.CharField(max_length=100, verbose_name='클래스명')),
                ('classStartDate', models.DateField(verbose_name='시작일')),
                ('classEndDate', models.DateField(verbose_name='종료일')),
                ('interestID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='meeting_app.interests', verbose_name='관련관심사')),
            ],
            options={
                'verbose_name': '클래스',
                'verbose_name_plural': '클래스들',
                'db_table': 'class',
                'ordering': ['-classID'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postID', models.AutoField(primary_key=True, serialize=False, verbose_name='게시글ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('category', models.CharField(choices=[('notice', '공지'), ('review', '후기'), ('general', '일반')], default='general', max_length=50, verbose_name='카테고리')),
                ('writeDate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='meeting_app.member', verbose_name='작성자')),
                ('class_classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='meeting_app.class', verbose_name='클래스')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글들',
                'db_table': 'post',
                'ordering': ['-writeDate'],
            },
        ),
        migrations.CreateModel(
            name='Sugang',
            fields=[
                ('sugangID', models.AutoField(primary_key=True, serialize=False, verbose_name='수강ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='신청일시')),
                ('class_classID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugang_set', to='meeting_app.class', verbose_name='클래스')),
                ('member_accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugang_set', to='meeting_app.member', verbose_name='회원')),
            ],
            options={
                'verbose_name': '수강신청',
                'verbose_name_plural': '수강신청들',
                'db_table': 'sugang',
                'ordering': ['-registration_date'],
                'unique_together': {('class_classID', 'member_accountID')},
            },
        ),
        migrations.CreateModel(
            name='MemberInterests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_interests', to='meeting_app.interests', verbose_name='관심사')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_interests', to='meeting_app.member', verbose_name='회원')),
            ],
            options={
                'verbose_name': '회원관심사',
                'verbose_name_plural': '회원관심사들',
                'db_table': 'memberInterests',
                'unique_together': {('member', 'interests')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceID', models.AutoField(primary_key=True, serialize=False, verbose_name='출석ID')),
                ('attendDate', models.DateField(verbose_name='출석일')),
                ('attendanceStatus', models.CharField(choices=[('present', '출석'), ('absent', '결석'), ('late', '지각')], default='present', max_length=20, verbose_name='출석상태')),
                ('sugang_sugangID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to='meeting_app.sugang', verbose_name='수강신청')),
            ],
            options={
                'verbose_name': '출석',
                'verbose_name_plural': '출석들',
                'db_table': 'attendance',
                'ordering': ['-attendDate'],
                'unique_together': {('sugang_sugangID', 'attendDate')},
            },
        ),
    ]
